default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: cork-shop_development

test:
  <<: *default
  database: cork-shop_test

production:
  <<: *default
  database: cork-shop_production
  username: cork-shop
  password: <%= ENV['CORK-SHOP_DATABASE_PASSWORD'] %>
