default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: store_development
test:
  <<: *default
  database: store_test

production:
  <<: *default
  database: store_production
  username: store
  password: <%= ENV['STORE_DATABASE_PASSWORD'] %>
